### PR TITLE
Codenervemerge

### PR DESCRIPTION
**Pull request by fazreil**
Hi,

This PR might be the one non-called for. I was cloning ifenil's repo (https://github.com/ifenil/Let-Us-Java) one of your forks before realizing this repo.

I was working on your codebase to refactor them into maven convention, therefore you can manage them using maven. Maven is useful in managing your java codebase so that you are able to see the whole landscape of your code in parent/child perspective. Using certain maven goals I was able to create a document of your java codebase. I wrote more about them in the README, check it out.

I have also implemented github actions so that every pull-request and commits into master is being built off in github without you need to compile it on your own.

I have a build before I merge this code into my master, check it out:
https://github.com/fazreil/Let-Us-Java/runs/1238170673

I wish my pull request get accepted. It would be cool to see this awesome repo being turned into Maven project.

### CODE REVIEW

**Comment by fazreil** [comment]
there are more comprehensive changes I list down in ifenil's PR page:

In this pull request, I have implemented maven build. To do that I have to reorganize the whole project into maven directory structure. Don't worry because the committer's contribution for each line of the code (when you git blame) is still intact.

Here are some key points for the refactorization:
- The whole project are structured as a children (modules) of a parent project called Let-Us-Java
- Each of the individual projects are modules, where they may build on its own
- There are some project I need to rename just to make them follow Java naming convention (like class name should be similar to the file name, java files should be camel case, take out spaces between names)
- Fixed compilation issue in Tree (https://github.com/fazreil/Let-Us-Java/commit/004fea54a01dd16d984370b5cf6ca517fe12f478)
- Fixed code for Tower of Hanoi (https://github.com/fazreil/Let-Us-Java/commit/a940fe80a7e1d868350f3020a36bf1d3de0f8d64)
- Fixed dependency for OTPGenerator to use commons-lang library (https://github.com/fazreil/Let-Us-Java/commit/9cd215251b0a00e56a1d8b674fe27018b42ea5c8)
- Added reporting feature in pom file to allow document generation. This will allow generation of the site for this project with the javadoc
- Added profile to do documentation and regular code compilation
- updated readme to include maven compilation guide
- included myself as one of the contributor :smiley: 

Bonus
- added github actions to build and document this project upon push to master.

I appreciate your time spent reading this pull request. Thank you.

You may review [my actions page](https://github.com/fazreil/Let-Us-Java/actions/runs/299523563) if the code builds accordingly. Project [documentation is also uploaded](https://github.com/fazreil/Let-Us-Java/suites/1319652312/artifacts/20976985) in the github actions tab for you to review before merging.

**Comment by fazreil** [comment]
You may check the build when I merge new @mKittyD @chinmaychahar and Acentari's code

**Comment by Pradyuman7** [comment]
That is a very awesome thing to do @fazreil, I was also working on making this a maven module, and I had just started with the setup, but you've already added so much. That's great. I have checked the new code setup and codebase and everything looks fie to me. Please let me know once you have added the latest code from @mKittyD and @chinmaychahar and I will look into merging this PR.

Nice work again 🎉

**Comment by fazreil** [comment]
Hey, thanks man. I apologize for the sloppy merging work. I am going to fix that real quick.

**Comment by fazreil** [comment]
@Pradyuman7 I have fixed the merge with @mKittyD. 
Changes by @chinmaychahar is incorporated as in previous commit. I have refactored his StackExceptionHandling to:
https://github.com/fazreil/Let-Us-Java/blame/codenervemerge/Stacks/src/main/java/StackExceptionHandling.java

Here is the build of that commit: https://github.com/fazreil/Let-Us-Java/runs/1240774213?check_suite_focus=true

Cheers

**Comment by Pradyuman7** [comment]
Awesome work again @fazreil, everything looks great 👍

**Pull request merged**
