### PR TITLE
Armstrong Number

### PR DESCRIPTION
**Pull request by UdbhavJain**
## Code contribution
- [x] Read through [contributing.md](https://github.com/CodeNerve/Let-Us-Java/blob/master/CONTRIBUTING.md)
- [x] All the code files are in a relevant directory
- [x] Code is only in java (and the files have .java extension), no other files (e.g. .class files) are included
- [x] The code is not already present in the repository
- [x] The contribution is meaninful and not just a simple print statement
- [x] The build passes for your PR

---

## ReadMe contribution
- [x] Formatting is good and not messy
- [x] The PR has meaninful contribution to make the repository better and not just typos or such small changes

### CODE REVIEW

**Comment by Pradyuman7** [comment]
Thanks for contributing, please go through the PR guideline checkboxes to make a valid contribution

**Comment by UdbhavJain** [comment]
> Thanks for contributing, please go through the PR guideline checkboxes to make a valid contribution

I have checked all the check boxes please merge my code

**Comment by Pradyuman7** [comment]
There are still a lot of issues in the PR, can you please try to fix them. You can go through the checklist in the PR and that should give you the idea of what to fix

**Comment by Pradyuman7** [comment]
Closing this PR for now, feel free to reopen if you'd like to work on it

**Pull request closed without merging**
