### PR TITLE
hotelManagement.java

### PR DESCRIPTION
**Pull request by Tanay-Dwivedi**
A simple Hotel Management System program in java. Have Fun😊😊😊

### CODE REVIEW

**Comment by Pradyuman7** [comment]
Please create a `java` file and name the class according to the file name (and not your name). Please refer Contributing.md for more info.

**Comment by Tanay-Dwivedi** [comment]
> Please create a `java` file and name the class according to the file name (and not your name). Please refer Contributing.md for more info.

done😊

**Comment by Pradyuman7** [comment]
@Tanay-Dwivedi can you also place your code in a relevant directory please? If you find no relevant directory existing, you can make a new one yourself.

**Comment by Pradyuman7** [comment]
Closing this redundant PR since the other one is merged now

**Comment by Tanay-Dwivedi** [comment]
> Closing this redundant PR since the other one is merged now

ok😊😊

**Pull request closed without merging**
