### PR TITLE
Added Optimised Fibonacci Series

### PR DESCRIPTION
**Pull request by harshsingh-io**
## Code contribution
- [x] Read through [contributing.md](https://github.com/CodeNerve/Let-Us-Java/blob/master/CONTRIBUTING.md)
- [x] All the code files are in a relevant directory
- [x] Code is only in java (and the files have .java extension), no other files (e.g. .class files) are included
- [x] The code is not already present in the repository
- [x] The contribution is meaninful and not just a simple print statement
- [x] The build passes for your PR

---

## ReadMe contribution
- [x] Formatting is good and not messy
- [x] The PR has meaninful contribution to make the repository better and not just typos or such small changes

### CODE REVIEW

**Comment by harshsingh-io** [comment]
This PR solves issue #474

**Comment by Pradyuman7** [comment]
Thanks for contributing, I am not sure this code needs a directory of it's own, please move it some other existing relevant directory and make sure that it's not contributed before. I think fibonacci is already present in the algorithms

**Comment by harshsingh-io** [comment]
@Pradyuman7 this code of fibonacci series runs in **Linear Time Complexity O(1)**  but the code in uploaded fibonacci series in your repository runs in **exponential time complexity O(2^n)**  you can try to run code of your repo's fibbo series for "n=50" it will stuck.  and i made the seperate directory for your convenience 😅

**Comment by Pradyuman7** [comment]
That's true, since this is not the same algorithm, it should be fine, but can you please add it to the Algorithms directory, adding it a new specific directory doesn't really make sense

**Comment by harshsingh-io** [comment]
@Pradyuman7 sure i am gonna do this.

**Comment by Pradyuman7** [comment]
Since hacktoberfest is over now, I am closing this PR, but feel free to reopen if you'd like to work on it

**Pull request closed without merging**
