### PR TITLE
Create sendEmail.java

### PR DESCRIPTION
**Pull request by lakshyatyagi24-1**
## Code contribution
- [x] Read through [contributing.md](https://github.com/CodeNerve/Let-Us-Java/blob/master/CONTRIBUTING.md)
- [x] All the code files are in a relevant directory
- [x] Code is only in java (and the files have .java extension), no other files (e.g. .class files) are included
- [x] The code is not already present in the repository
- [x] The contribution is meaninful and not just a simple print statement
- [x] The build passes for your PR

---

## ReadMe contribution
- [ ] Formatting is good and not messy
- [ ] The PR has meaninful contribution to make the repository better and not just typos or such small changes

### CODE REVIEW

**Comment by Pradyuman7** [comment]
Thanks for contributing, please go through the checklist above to make a valid contribution

**Comment by lakshyatyagi24-1** [comment]
@Pradyuman7 Please check now

**Comment by Pradyuman7** [comment]
This code is not valid Java, since it would need to be in a class. Also, I think this can be moved to small projects directory

**Comment by lakshyatyagi24** [comment]
Can we please close this PR

**Pull request closed without merging**
