### PR TITLE
Created Insertion sort algorithm

### PR DESCRIPTION
**Pull request by sukumarc**
Added new Insertion sort algorithm ! Happy Hacktoberfest !
#3

### CODE REVIEW

**Comment by Pradyuman7** [comment]
@sukumarc thank you for contributing, but could you please add some other interesting code of your choice as insertion sort has already been added. Thank you!

**Comment by sukumarc** [comment]
@Pradyuman7 thank you for reviewing it, I don't see insertion sort inside sorting folder. Can you please look on this again ?

**Comment by Pradyuman7** [comment]
My mistake @sukumarc, I was thinking about the Selection sort. Great work 🎉

**Comment by sukumarc** [comment]
@Pradyuman7  Thank you for accepting, can you please add hacktoberfest-accepted label 🥳

**Pull request merged**
