### PR TITLE
Removed Duplicates and placed all the similar topic codes in the same folder #347

### PR DESCRIPTION
**Pull request by aryanlath**
## Code contribution
- [ ] Read through [contributing.md](https://github.com/CodeNerve/Let-Us-Java/blob/master/CONTRIBUTING.md)
- [ ] All the code files are in a relevant directory
- [ ] Code is only in java (and the files have .java extension), no other files (e.g. .class files) are included
- [ ] The code is not already present in the repository
- [ ] The contribution is meaninful and not just a simple print statement
- [ ] The build passes for your PR

---

## ReadMe contribution
- [ ] Formatting is good and not messy
- [ ] The PR has meaninful contribution to make the repository better and not just typos or such small changes

### CODE REVIEW

**Comment by Pradyuman7** [comment]
The build seems to be failing, can you please check. Also, please make sure to remove the empty directories if you move all the files from a directory to another

**Comment by aryanlath** [comment]
Ok Thanks I will look into it

**Comment by aryanlath** [comment]
Hi! I have created a new folder of Data Structure where I have kept all the codes for the different data structures and maybe 
that is what causing an issue.

**Comment by Pradyuman7** [comment]
The project is using maven, you might have to fix the files for that if you refactor the directory

**Comment by Pradyuman7** [comment]
Closing this PR for now, feel free to reopen if you'd like to work on it

**Pull request closed without merging**
