### PR TITLE
 createatree.java

### PR DESCRIPTION
**Pull request by prasantbajpai007**

### CODE REVIEW

**Comment by Pradyuman7** [comment]
@prasantbajpai007 can you add `.java` extension to your files please?

**Comment by prasantbajpai007** [comment]
plz merge my pull request

**Comment by Pradyuman7** [comment]
@prasantbajpai007 please read CONTRIBUTING.md file to fix stuff. This all should be placed in a relevant directory from the project, and please make sure that the class names inside the file are same as the file names.

**Comment by Pradyuman7** [comment]
Closing due to inactivity

**Pull request closed without merging**
