### PR TITLE
Create checkarrayrotation.java

### PR DESCRIPTION
**Pull request by alok007kr**
I have added code to check array rotation in array.

## Code contribution
- [x] Read through [contributing.md](https://github.com/CodeNerve/Let-Us-Java/blob/master/CONTRIBUTING.md)
- [x] All the code files are in a relevant directory
- [x] Code is only in java (and the files have .java extension), no other files (e.g. .class files) are included
- [x] The code is not already present in the repository
- [x] The contribution is meaninful and not just a simple print statement
- [x] The build passes for your PR

---

## ReadMe contribution
- [x] Formatting is good and not messy
- [x] The PR has meaninful contribution to make the repository better and not just typos or such small changes

### CODE REVIEW

**Comment by alok007kr** [comment]
Hey @Pradyuman7 i have added code to check array rotation . please merge it. Thank you

**Comment by Pradyuman7** [comment]
Thanks for contributing, I don't think this code needs a new directory of it's own, can you try finding an existing directory where this code would should go? e.g. Algorithms?

**Comment by alok007kr** [comment]
Ok sure... I will put this on algorithm directory. But kindly merge it
please . Thanks & Regards...


Happy Diwali also

**Comment by Pradyuman7** [comment]
Please update the PRs #437, #438, #439 as well with this. Once you're done, I'll merge the PRs!

Cheers,
Happy Diwali to you as well

**Comment by alok007kr** [comment]
Done. If there is any problem please let me know.

**Pull request merged**
