### PR TITLE
Arranging Coins in java

### PR DESCRIPTION
**Pull request by nigotia30**
You have a total of n coins that you want to form in a staircase shape, where every k-th row must have exactly k coins.

Given n, find the total number of full staircase rows that can be formed.

n is a non-negative integer and fits within the range of a 32-bit signed integer.

Example 1:

n = 5

The coins can form the following rows:
¤
¤ ¤
¤ ¤

Because the 3rd row is incomplete, we return 2.
Example 2:

n = 8

The coins can form the following rows:
¤
¤ ¤
¤ ¤ ¤
¤ ¤

Because the 4th row is incomplete, we return 3.

### CODE REVIEW

**Comment by Pradyuman7** [comment]
Please add your code in a `.java` file rather than a text one with no file extension, also please add the question of the code in the `.java` file in form of a comment.

**Comment by Pradyuman7** [comment]
Closing this PR due to inactivity

**Comment by nigotia30** [comment]
Respected Sir, 
Sorry for not being able to reply to the changes. I was not able to get a notification for the same because my phone got damaged. This is absolutely unethical, i had commited my code 3 days back and i got a reply yesterday for the same. You just cannot close the request due to being inactive for a day. Its completely fine if you have but just try to give it a thought on others behave.

**Comment by Pradyuman7** [comment]
Hello @nigotia30 you don't have to be so serious about this, you can just reopen the PR and it won't affect your Hacktoberfest participation in any way. Marking a PR as invalid counts as wrong. I am reopening the PR and you can apply the changes and commit. I am happy to merge those changes.

Happy coding!

**Comment by nigotia30** [comment]
Thank you so much sir for understanding the situation. Its not just because of hacktoberfest, i somehow felt what was done was not right. So thought of discussing and asking for an explaination sir. I'll surely make the changes and would continue to contribute for the open source community.

**Review by Pradyuman7 — APPROVED** [review]

**Pull request merged**
